library(ggplot2)
library(class)
library(rpart)
library(rpart.plot)

load("/Users/beth/Documents/mssm/modern-clinical-data-science/code/mixture.example.RData")
df <- data.frame(x1 = mixture.example$x[,1], x2 = mixture.example$x[,2], y = mixture.example$y)
x.grid <- seq(min(df$x1), max(df$x1), 0.1)
y.grid <- seq(min(df$x2), max(df$x2), 0.1)
df$y <- 1 - df$y # fix issue of class labeling

# Figure 2.1 (just the dataset)
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y > 0.5), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2), alpha = 0.5, data = xy.grid, colour = "gray50", size = 0.02) + 
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + 
  theme(axis.text = element_blank()) + 
  theme(legend.position = "bottom", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
  scale_colour_manual(name = "ER Admission?", labels = c("no", "yes"), values = c("#00bfc4", "#f8766d"))
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-just-data.png", height=4.5, width=4, units="in", dpi=300)

# Figure 2.1 (logistic regression)
m <- glm(y ~ x1 + x2, data = df, family = "binomial")
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
xy.grid$yhat <- predict(m, xy.grid, type = "response")
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y > 0.5), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat > 0.5), alpha = 0.5, data = xy.grid, size = 0.02) + 
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + theme(axis.text = element_blank()) + 
  scale_colour_manual(name = "ER Admission?", labels = c("no", "yes"), values = c("#00bfc4", "#f8766d")) +
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20") + 
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank())
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-logistic.png", height=4, width=4, units="in", dpi=300)

# Figure 2.1 (logistic regression with probabilities)
m <- glm(y ~ x1 + x2, data = df, family = "binomial")
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
xy.grid$yhat <- predict(m, xy.grid, type = "response")
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat), alpha = 1.0, data = xy.grid, size = 0.02) + 
  scale_colour_gradient(low = "#00bfc4", high = "#f8766d") +
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + theme(axis.text = element_blank()) + 
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20", 
               linetype = "dashed") + 
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank())
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-logistic-prob.png", 
       height=4, width=4, units="in", dpi=300)

# Figure 2.1 (logistic regression with probabilities and axis labels)
m <- glm(y ~ x1 + x2, data = df, family = "binomial")
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
xy.grid$yhat <- predict(m, xy.grid, type = "response")
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat), alpha = 1.0, data = xy.grid, size = 0.02) + 
  scale_colour_gradient(low = "#00bfc4", high = "#f8766d") +
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + 
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20", 
               linetype = "dashed") + 
  theme(legend.position = "none")
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-logistic-prob-axes.png", 
       height=4, width=4, units="in", dpi=300)

# Logistic regression with probabilities from the side
summary(m)
df$pred_prob <- predict(m, df, type = "response")
df$pred_link <- predict(m, df, type = "link")
p <- ggplot(df) + 
  geom_point(aes(x = pred_link, y = pred_prob, colour = y), pch = 21, fill = NA) + 
  scale_colour_gradient(low = "#00bfc4", high = "#f8766d") +
  theme_minimal() + 
  xlab("0.978 + 0.134 x1 - 1.398 x2") + 
  ylab("Predicted Probability P(Y=1)") + 
  geom_vline(xintercept = 0, linetype = "dashed", colour = "gray60") + 
  geom_hline(yintercept = 0.5, linetype = "dashed", colour = "gray60") + 
  theme(legend.position = "none")
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-logistic-prob-link.png", 
       height=4, width=5, units="in", dpi=300)

# Figure 2.1 (knn with k = 15)
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
m <- knn(df[,1:2], xy.grid, as.factor(df[,3]), k=15, prob=TRUE)
xy.grid$yhat <- as.numeric(as.character(m))
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y > 0.5), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat > 0.5), alpha = 0.5, data = xy.grid, size = 0.02) + 
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + theme(axis.text = element_blank()) + 
  scale_colour_manual(name = "ER Admission?", labels = c("no", "yes"), values = c("#00bfc4", "#f8766d")) +
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20") + 
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-knn-15.png", height=4, width=4, units="in", dpi=300)

# Figure 2.1 (knn with k = 15) with probabilities
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
m <- knn(df[,1:2], xy.grid, as.factor(df[,3]), k=15, prob=TRUE)
xy.grid$votes <- as.numeric(as.character(attr(m, "prob")))
xy.grid$class <- as.numeric(as.character(m))
xy.grid$yhat <- ifelse(xy.grid$class == 1, xy.grid$votes, 1 - xy.grid$votes)
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat), alpha = 1.0, data = xy.grid, size = 0.02) + 
  scale_colour_gradient(low = "#00bfc4", high = "#f8766d") +
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + theme(axis.text = element_blank()) + 
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20", 
               linetype = "dashed") + 
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-knn-15-prob.png", height=4, width=4, units="in", dpi=300)

# Figure 2.1 (knn with k = 3)
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
m <- knn(df[,1:2], xy.grid, as.factor(df[,3]), k=3, prob=TRUE)
xy.grid$yhat <- as.numeric(as.character(m))
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y > 0.5), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat > 0.5), alpha = 0.5, data = xy.grid, size = 0.02) + 
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + theme(axis.text = element_blank()) + 
  scale_colour_manual(name = "ER Admission?", labels = c("no", "yes"), values = c("#00bfc4", "#f8766d")) +
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20") + 
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-knn-3.png", height=4, width=4, units="in", dpi=300)

# Figure 2.1 (knn with k = 50)
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
m <- knn(df[,1:2], xy.grid, as.factor(df[,3]), k=50, prob=TRUE)
xy.grid$yhat <- as.numeric(as.character(m))
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y > 0.5), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat > 0.5), alpha = 0.5, data = xy.grid, size = 0.02) + 
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + theme(axis.text = element_blank()) + 
  scale_colour_manual(name = "ER Admission?", labels = c("no", "yes"), values = c("#00bfc4", "#f8766d")) +
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20") + 
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-knn-50.png", height=4, width=4, units="in", dpi=300)

# Figure 2.1 (knn with k = 100)
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
m <- knn(df[,1:2], xy.grid, as.factor(df[,3]), k=100, prob=TRUE)
xy.grid$yhat <- as.numeric(as.character(m))
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y > 0.5), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat > 0.5), alpha = 0.5, data = xy.grid, size = 0.02) + 
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + theme(axis.text = element_blank()) + 
  scale_colour_manual(name = "ER Admission?", labels = c("no", "yes"), values = c("#00bfc4", "#f8766d")) +
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20") + 
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-knn-100.png", height=4, width=4, units="in", dpi=300)

# Figure 2.1 (decision tree)
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
m <- rpart(as.factor(y) ~ x1 + x2, data = df)
xy.grid$yhat <- predict(m, xy.grid)[,2]
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y > 0.5), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat > 0.5), alpha = 0.5, data = xy.grid, size = 0.02) + 
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + theme(axis.text = element_blank()) +
  scale_colour_manual(name = "ER Admission?", labels = c("no", "yes"), values = c("#00bfc4", "#f8766d")) +
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20") + 
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-decision-tree.png", height=4, width=4, units="in", dpi=300)

# plot the decision tree itself
palette <- colorRampPalette(colors=c("#00BFC4", "#F8766D"))
rpart.plot(m, box.palette=palette(20))

# decision tree with probabilities
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
m <- rpart(as.factor(y) ~ x1 + x2, data = df)
xy.grid$yhat <- predict(m, xy.grid)[,2]
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat), alpha = 1.0, data = xy.grid, size = 0.02) + 
  scale_colour_gradient(low = "#00bfc4", high = "#f8766d") +
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + theme(axis.text = element_blank()) + 
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20", 
               linetype = "dashed") + 
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-decision-tree-prob.png", height=4, width=4, units="in", dpi=300)

# Figure 2.1 (random forest)
library(randomForest)
m <- randomForest(as.factor(y) ~ x1 + x2, data = df, do.trace = TRUE)
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
xy.grid$yhat <- predict(m, xy.grid, type = "prob")[,2]
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y > 0.5), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat > 0.5), alpha = 0.5, data = xy.grid, size = 0.02) + 
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + theme(axis.text = element_blank()) + 
  scale_colour_manual(name = "ER Admission?", labels = c("no", "yes"), values = c("#00bfc4", "#f8766d")) +
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20") + 
  theme(legend.position = "none", panel.grid.major = element_blank(), panel.grid.minor = element_blank())
ggsave(p, filename = "/Users/beth/Documents/mssm/modern-clinical-data-science/figures/esl-rf.png", height=4, width=4, units="in", dpi=300)
