---
title: "Feature Selection Analysis"
output: html_notebook
---

Libraries.

```{r setup}
library(tidyverse)
library(wesanderson)
library(MASS)
library(GGally)
library(caret)
library(rpart)
library(rpart.plot)
library(glmnet)
```

Use Pima dataset.

```{r}
d <- read.csv("../data/pima-indians-diabetes-database.csv")
```

Individual feature histograms.

```{r}
pal <- wes_palette("Moonrise3", n = 8, type = "continuous") 
alpha_val = 0.7
img_height = 3.0
img_width = 6.0

p <- ggplot(d) + 
  geom_histogram(aes(x = Pregnancies), binwidth = 1, fill = pal[1], alpha = alpha_val) + 
  theme_minimal() + ylab("Count")
ggsave(p, filename = "../img/pima-pregnancies.png", height=img_height, width=img_width, 
       units="in", dpi=300)

p <- ggplot(d) + 
  geom_histogram(aes(x = Glucose), binwidth = 10, fill = pal[2], alpha = alpha_val) + 
  theme_minimal() + ylab("Count")
ggsave(p, filename = "../img/pima-glucose.png", height=img_height, width=img_width, 
       units="in", dpi=300)

p <- ggplot(d) + 
  geom_histogram(aes(x = BloodPressure), binwidth = 5, fill = pal[3], alpha = alpha_val) + 
  theme_minimal() + ylab("Count")
ggsave(p, filename = "../img/pima-blood-pressure.png", height=img_height, width=img_width, 
       units="in", dpi=300)

p <- ggplot(d) + 
  geom_histogram(aes(x = SkinThickness), binwidth = 5, fill = pal[4], alpha = alpha_val) + 
  theme_minimal() + ylab("Count")
ggsave(p, filename = "../img/pima-skin-thickness.png", height=img_height, width=img_width, 
       units="in", dpi=300)

p <- ggplot(d) + 
  geom_histogram(aes(x = Insulin), binwidth = 30, fill = pal[5], alpha = alpha_val) + 
  theme_minimal() + ylab("Count")
ggsave(p, filename = "../img/pima-insulin.png", height=img_height, width=img_width, 
       units="in", dpi=300)

p <- ggplot(d) + 
  geom_histogram(aes(x = BMI), binwidth = 5, fill = pal[6], alpha = alpha_val) + 
  theme_minimal() + ylab("Count")
ggsave(p, filename = "../img/pima-bmi.png", height=img_height, width=img_width, 
       units="in", dpi=300)

p <- ggplot(d) + 
  geom_histogram(aes(x = DiabetesPedigreeFunction), binwidth = 0.1, fill = pal[7], alpha = alpha_val) + 
  theme_minimal() + ylab("Count")
ggsave(p, filename = "../img/pima-diab-ped-function.png", height=img_height, width=img_width,
       units="in", dpi=300)

p <- ggplot(d) + 
  geom_histogram(aes(x = Age), binwidth = 5, fill = pal[8], alpha = alpha_val) + 
  theme_minimal() + ylab("Count")
ggsave(p, filename = "../img/pima-age.png", height=img_height, width=img_width, 
       units="in", dpi=300)
```

Log-transforming disease pedigree function.

```{r}
d$LogDiabetesPedigreeFunction = log10(d$DiabetesPedigreeFunction)
p <- ggplot(d) + 
  geom_histogram(aes(x = LogDiabetesPedigreeFunction), binwidth = 0.1, fill = pal[7], alpha = 1.0) + 
  theme_minimal() + ylab("Count")
ggsave(p, filename = "../img/pima-diab-ped-function-log.png", height=img_height, width=img_width,
       units="in", dpi=300)
```

Correlation matrix of dataset.

```{r}
p <- ggpairs(d[,1:8], aes(alpha = 0.2)) + 
  theme_minimal() + 
  scale_colour_manual(values = c("turquoise4")) + scale_fill_manual(values = c("gray30"))
ggsave(p, filename = "../img/pima-ggpairs.png", height=8, width=14, units="in", dpi=300)
```

Unadjusted vs. adjusted p-values.

```{r}
m <- glm(Outcome ~ Age, data = d, family = "binomial")
summary(m)
m <- glm(Outcome ~ . - LogDiabetesPedigreeFunction, data = d, family = "binomial")
summary(m)
```

Forward selection using MASS.

```{r}
d <- read.csv("../data/pima-indians-diabetes-database.csv")

fit1 <- glm(Outcome ~ ., data = d, family = "binomial")
fit2 <- glm(Outcome ~ 1, data = d, family = "binomial")
stepAIC(fit1, direction="backward")
stepAIC(fit2, direction="forward", scope=list(upper=fit1,lower=fit2))
stepAIC(fit2, direction="both", scope=list(upper=fit1,lower=fit2))
```

Decision tree.

```{r}
m <- rpart(Outcome ~ ., data = d)
palette <- colorRampPalette(colors=c("#00BFC4", "#F8766D"))
png(filename = "../img/pima-decision-tree.png", height=4, width=6, units="in", res=300)
rpart.plot(m, box.palette=palette(20))
dev.off()
```

Lasso-penalized logistic regression.

```{r}
X <- model.matrix(Outcome ~ . - 1, data=d)
y <- as.factor(d$Outcome)
c <- cv.glmnet(X, y, family = "binomial")
plot(c)
predict(c, type = "coef", s = "lambda.min")
c
```

