---
title: "Fitting and Interpreting GLMs"
output: html_notebook
---

## Libraries

```{r setup}
library(ggplot2)
library(scales)
library(dplyr)
library(survival)
library(survminer)
library(lubridate)
library(tidyr)
library(stringr)
library(forcats)
library(wesanderson)
library(class)
library(rpart)
library(rpart.plot)
```

## Linear regression

Data for linear regression case study.

```{r}
load("../data/mixture.example.RData")
intercept = 50.0
coef_x1 = 10.0
coef_x2 = -2.0
set.seed(1000)
df <- data.frame(x1 = mixture.example$x[,1], x2 = mixture.example$x[,2]) %>%
  mutate(y = intercept + coef_x1 * x1 + coef_x2 * x2 + rnorm(length(x1), 0, 5))
x.grid <- seq(min(df$x1), max(df$x1), 0.1)
y.grid <- seq(min(df$x2), max(df$x2), 0.1)
```

Fit linear regression model two ways.

```{r}
m1 <- lm(y ~ x1 + x2, data = df)
summary(m1)
```

```{r}
m2 <- glm(y ~ x1 + x2, data = df, family = "gaussian")
summary(m2)
```

```{r}
x.grid <- seq(min(df$x1), max(df$x1), 0.05)
y.grid <- seq(min(df$x2), max(df$x2), 0.05)
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
m <- lm(y ~ x1 + x2, data = df)
xy.grid$yhat <- predict(m, xy.grid)
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y, fill = y), pch = 21) + 
  geom_point(aes(x = x1, y = x2, colour = yhat), alpha = 0.4, data = xy.grid, size = 0.5) + 
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + 
  scale_fill_gradient(name = "Recurrence\nBiomarker (y)", low = "#00bfc4", high = "#f8766d") +
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = quantile(xy.grid$yhat, seq(0, 1, 0.25)), 
               data = xy.grid, colour = "gray30") + 
  scale_colour_gradient(name = "Recurrence\nBiomarker (y)", low = "#00bfc4", high = "#f8766d") + 
  theme(legend.position = "none") + 
  coord_cartesian(xlim=c(min(xy.grid$x1),max(xy.grid$x1)), ylim=c(min(xy.grid$x2),max(xy.grid$x2)))
print(p)
ggsave(p, filename = "../img/esl-reg-linear-wlabels.png", height=4, width=4, units="in", dpi=300)
```

## Logistic regression

Data for logistic regression case study. 

```{r}
load("../data/mixture.example.RData")
df <- data.frame(x1 = mixture.example$x[,1], x2 = mixture.example$x[,2], y = mixture.example$y)
x.grid <- seq(min(df$x1), max(df$x1), 0.1)
y.grid <- seq(min(df$x2), max(df$x2), 0.1)
df$y <- 1 - df$y # fix issue of class labeling
```

Fit logistic regression model.

```{r}
m3 <- glm(y ~ x1 + x2, data = df, family = "binomial")
summary(m3)
```

```{r}
xy.grid <- expand.grid(x.grid, y.grid)
names(xy.grid) <- c("x1", "x2")
xy.grid$yhat <- predict(m3, xy.grid, type = "response")
p <- ggplot(df) + 
  geom_point(aes(x = x1, y = x2, colour = y), pch = 21, fill = NA) + 
  geom_point(aes(x = x1, y = x2, colour = yhat), alpha = 1.0, data = xy.grid, size = 0.02) + 
  scale_colour_gradient(low = "#00bfc4", high = "#f8766d") +
  theme_minimal() + 
  xlab("Disease Severity Score (x1)") + 
  ylab("Social Determinants Score (x2)") + 
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = 0.5, data = xy.grid, colour = "gray20", 
               linetype = "solid") + 
  stat_contour(aes(x = x1, y = x2, z = yhat), breaks = c(0.25, 0.75), data = xy.grid, colour = "gray30", 
               linetype = "dashed") +
  theme(legend.position = "none")
ggsave(p, filename = "../img/esl-logistic-prob-axes.png", height=4, width=4, units="in", dpi=300)
```

## Case study: linear regression

```{r}
d <- read.csv("../data/linear-small-cities-data.csv")
m <- glm(MORT ~ PRECIP + EDUC + NONWHITE + NOX + SO2, data = d, family = "gaussian")
summary(m)
```

```{r}
d <- read.csv("../data/linear-small-cities-data.csv")
m <- lm(MORT ~ PRECIP + EDUC + NONWHITE + NOX + SO2, data = d)
summary(m)
```
